### ISSUE TITLE
Closing connection

### ISSUE THREAD

**Issue by jrschumacher** [titarenko/worque#10]
Is there a way to close a connection?

**Comment by titarenko** [comment]
Right now – no. Library was intended to represent foundation for task server and was envisioned to run as long as task server runs. But if this feature would be useful, it's not so difficult to add it.

**Comment by jrschumacher** [comment]
@titarenko no that's fine. This is what I'm doing as well but if the server crashes is it an issue if the server doesn't close the connection to rabbitmq cleanly.

**Comment by titarenko** [comment]
RabbitMQ handles such unexpected disconnects. So no resource leaking will be caused on server side. What is for client (your app), it's already crashed (in case about which we are talking), so OS should clean up any open handles (socket, file handles, etc), so again, there should be no problem with client side either.

**Comment by jrschumacher** [comment]
@titarenko thanks for the heads up
