### ISSUE TITLE
Detail about subscriber schedule

### ISSUE THREAD

**Issue by jrschumacher** [titarenko/worque#12]
I'm a little confused about the subscriber scheduler could you describe its purpose?

**Comment by titarenko** [comment]
It's just chainable API method calls (not builder API): `queue('name')` constructs queue and then exposes its chainable API, so (as in example), if you are hosting both scheduler and worker in a single process, you can first setup worker (handler), by subscribing to queue (`subscribe()`), and then setup scheduler by calling `schedule()`. You can change the order of method calls, result will be the same.

**Comment by jrschumacher** [comment]
@titarenko so the scheduler acts like a cronjob? Does it check the server time to determine when to run?

**Comment by titarenko** [comment]
exactly. it uses [cron](https://www.npmjs.com/package/cron) behind the scenes.
