### ISSUE TITLE
Event emitted when client connects?

### ISSUE THREAD

**Issue by jrschumacher** [titarenko/worque#13]
Is there an event emitted when a client connect correctly? I'd like to configure my app to ensure it doesn't boot up before the client is connected.

**Comment by titarenko** [comment]
No, there is no such event. Errors should be handled as usual when dealing with promises:

```js
queue('my-queue')
  .subscribe(require('./my-message-handler'))
  .promise
  .catch(function (error) {
    console.error(error.stack);
  });
```

**Comment by titarenko** [comment]
If you haven't specified any `catch` statement, there will be `unhandledRejection`. More details in [bluebird docs](http://bluebirdjs.com/docs/api/error-management-configuration.html#global-rejection-events).

**Comment by jrschumacher** [comment]
Thanks I think I was able to figure something out.
