### ISSUE TITLE
I there's a way to scale worque schedule ?

### ISSUE THREAD

**Issue by fruch** [titarenko/worque#17]
the use case i'm talking about is schedule of a unique job
and we need the schedule to be runing in more then one process/mechine for redundency (in active-active mode)

I've found it wokring with: 
https://github.com/lykmapipo/kue-scheduler

but I need a rabbitmq backend, and I won't have access to redis

maybe this technique ?
https://www.rabbitmq.com/blog/2014/02/19/distributed-semaphores-with-rabbitmq/

event that thet bashed it a lot here:
https://aphyr.com/posts/315-jepsen-rabbitmq

**Comment by titarenko** [comment]
Hi, thanks for interest to this project!

Scaling is simple:

1. run this `scheduler.js` on single node (single OS process)
```js
const client = require('worque')('amqp://rabbit.dev/')
client('my task').schedule('3 * *')
```

2. run this worker (as OS process) as many times as you want in order to scale
`worker.js`
```
client('my task').subscribe(handler)

function handler () {
	return Promise.resolve().tap(function () {
		console.log(new Date(), process.pid, 'started working on "my task"')
	}).delay(5000).then(function () {
		console.log(new Date(), process.pid, 'finished working on "my task"')	
	})
}
```

P. S. Please note that in this example task requires 5 secs to complete and scheduler produces new one each 3 seconds, so at least 2 workers are needed to process such load.

I'm closing issue, reopen if something remains unclear.

**Comment by fruch** [comment]
I'm referring to the scale/redundancy of the scheduler, (I.e. not the work who process the jobs)

I want more then one process/machine doing the cronjob, as a backup to on another.

If my schedule process lost connectivity, or crash. It's one point of failure, and I want to be able to scale this into multiple regions, and make sure it will always run, and once it run the job, the job would be unique (I.e. as long I have one scheduler alive, and one worker alive)

kue-scheduler addresses this with using a redis backed lock on the insertion of the job to the queue.

One can argue you can do that lock inside the job itself (which is what I'll do for starter), I just think it's important enough pattern for building a "cloud"   service, that is would be awesome if it could be out of the box.

The only problem is that rabbitmq is not redis...

**Comment by titarenko** [comment]
I see. In my opinion, this is a job for tool on a lower level of abstraction (or deeper technology stack level, if you wish). Container (where node process runs) is restarted by cloud management solution (if needed, even on different physical node, if current one dies).

**Comment by titarenko** [comment]
P. S. Sorry for very brief first answer, I'm a bit tight on schedule with other activities, so didn't read all the details, just spotted `scheduling` and `scaling` and decided to answer quickly :)

**Comment by fruch** [comment]
Thanks for the prompt answer :)
